on:
  push:
    branches:
      - dev
      - qa
      - main


jobs:
  snowflake-query:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update

      - name: Download SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.28-linux_x86_64.bash

      - name: Install SnowSQL
        run: |
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.28-linux_x86_64.bash
          echo "export PATH=~/snowflake:$PATH" >> ~/.profile
          source ~/.profile


      - name: Configure SnowSQL
        run: |
          mkdir -p ~/.snowsql
          cat > ~/.snowsql/config << EOF
          [connections]
          accountname = nsiaocm-zm98259
          username = SANJAYS
          password = Temp@123$
          role = ACCOUNTADMIN
          database = TFDB
          schema = DEV
          EOF
          chmod 600 ~/.snowsql/config


      - name: Run SnowSQL show db Command
        run: snowsql -q "SHOW DATABASES;"
          
